#!/usr/bin/env node
/**
 * Deploy dataset-health + stripe-webhook edge functions and set owner-alert secrets.
 *
 * Requires in .env:
 *   SUPABASE_ACCESS_TOKEN  (from https://supabase.com/dashboard/account/tokens)
 *   RESEND_API_KEY         (re_… from Resend → API Keys)
 *
 * Optional in .env (defaults shown):
 *   ALERT_EMAIL=info@bluewaterintel.com
 *   ALERT_FROM=Bluewater Intel <alerts@bluewaterintel.com>
 *   CRON_SECRET=<auto-generated if missing>
 *
 * After this script:
 *   1. Run: npx supabase db push   (creates dataset_health tables)
 *   2. Paste supabase-fixes/dataset-health-cron.sql in Dashboard → SQL Editor
 */
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PROJECT_REF = "mealpzwbjamkjdrsszqe";
const SITE = "https://app.bluewaterintel.com";
const SUPABASE = join(ROOT, "node_modules", ".bin", "supabase");
const ENV_PATH = join(ROOT, ".env");

function loadEnv() {
  if (!existsSync(ENV_PATH)) return {};
  const out = {};
  for (const line of readFileSync(ENV_PATH, "utf8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i < 1) continue;
    out[t.slice(0, i)] = t.slice(i + 1).replace(/^["']|["']$/g, "");
  }
  return out;
}

function upsertEnv(key, value) {
  if (!existsSync(ENV_PATH)) return;
  let text = readFileSync(ENV_PATH, "utf8");
  const re = new RegExp(`^${key}=.*$`, "m");
  const line = `${key}=${value}`;
  text = re.test(text) ? text.replace(re, line) : `${text.trimEnd()}\n${line}\n`;
  writeFileSync(ENV_PATH, text);
}

function run(cmd, args, env = process.env) {
  const r = spawnSync(cmd, args, { cwd: ROOT, stdio: "inherit", env });
  if (r.status !== 0) process.exit(r.status ?? 1);
}

const envFile = loadEnv();
const cliEnv = {
  ...process.env,
  ...(envFile.SUPABASE_ACCESS_TOKEN ? { SUPABASE_ACCESS_TOKEN: envFile.SUPABASE_ACCESS_TOKEN } : {}),
};

if (!cliEnv.SUPABASE_ACCESS_TOKEN) {
  console.error(
    "Missing SUPABASE_ACCESS_TOKEN in .env\n" +
      "Get one at https://supabase.com/dashboard/account/tokens\n"
  );
  process.exit(1);
}

if (!envFile.RESEND_API_KEY || envFile.RESEND_API_KEY.includes("re_...")) {
  console.error(
    "Missing RESEND_API_KEY in .env\n" +
      "Get one at https://resend.com/api-keys and add:\n" +
      "  RESEND_API_KEY=re_...\n"
  );
  process.exit(1);
}

let cronSecret = envFile.CRON_SECRET;
if (!cronSecret || cronSecret.includes("generate-a-long")) {
  cronSecret = randomBytes(32).toString("hex");
  upsertEnv("CRON_SECRET", cronSecret);
  console.log("Generated CRON_SECRET and saved to .env");
}

const alertEmail = envFile.ALERT_EMAIL || "info@bluewaterintel.com";
const alertFrom = envFile.ALERT_FROM || "Bluewater Intel <alerts@bluewaterintel.com>";

run(SUPABASE, ["link", "--project-ref", PROJECT_REF], cliEnv);

const secrets = [
  `ALLOWED_ORIGINS=${SITE},https://coruscating-bunny-42b64d.netlify.app`,
  `RESEND_API_KEY=${envFile.RESEND_API_KEY}`,
  `ALERT_EMAIL=${alertEmail}`,
  `ALERT_FROM=${alertFrom}`,
  `CRON_SECRET=${cronSecret}`,
];
run(SUPABASE, ["secrets", "set", ...secrets], cliEnv);
run(SUPABASE, ["functions", "deploy", "dataset-health", "--no-verify-jwt"], cliEnv);
run(SUPABASE, ["functions", "deploy", "stripe-webhook", "--no-verify-jwt"], cliEnv);

// Write cron SQL with the real project ref + secret so it's ready to paste.
const cronSql = `-- Run once in Supabase Dashboard → SQL Editor
create extension if not exists pg_cron;
create extension if not exists pg_net;

select cron.schedule(
  'dataset-health-6h',
  '0 */6 * * *',
  $$
  select net.http_post(
    url     := 'https://${PROJECT_REF}.supabase.co/functions/v1/dataset-health',
    headers := jsonb_build_object('Content-Type','application/json','x-cron-secret','${cronSecret}'),
    body    := jsonb_build_object('action','run')
  );
  $$
);
`;
writeFileSync(join(ROOT, "supabase-fixes", "dataset-health-cron.sql"), cronSql);

console.log("\n✓ Secrets set; dataset-health + stripe-webhook deployed");
console.log("\nNext steps:");
console.log("  1. npx supabase db push");
console.log("  2. Paste supabase-fixes/dataset-health-cron.sql into Supabase → SQL Editor → Run");
console.log("  3. In the app: Menu → User Admin → System Health → Run check now");
